development:
  adapter: postgresql
  encoding: utf8
  database: abstractedly_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: abstractedly_test
  pool: 5
  timeout: 5000
